---
title: "Model Intercomparison File Format (MIF)"
author: "David Klein"
date: "16 April 2020"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MIF file format description}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The **Model Intercomparison File Format (MIF)** is the default file
format for data produced by Integrated Assessment Models. It is based on the
common format used for Model Intercomparison Projects such as EMF and SSP
with some slight changes/clarifications in its definition. For interactions
between models this format should be used. For everything else it is at least
recommended to use this format, too.

Aim of this standardization is to achieve a more flexible and smooth
communication between models and to facilitate the creation of aggregated
outputs from integrated assessment scenario runs which then can easily be
uploaded to external databases such as the EMF or SSP database. By using this
standard most of the required decisions for a working input output interface
between models have already been specified which significantly reduces the
required work to get a new interaction running.

## Definition

The format is characterized by the following features:
  
* The file ending is ".mif"
* The file is written in ASCII format
* Entries are separated with ";", every line ends with a ";"
* The file always contains a header
* The format of the header is: `Model;Scenario;Region;Variable;Unit;<ADDITIONAL_COLUMNS>;<YEARS>;`

 
The first 5 entries always have to exist, `<ADDITIONAL_COLUMNS>` is additional
information which can be added optionally (e.g. "Description") and `<YEARS>`
are the years for which data is delivered. `<YEARS>` are always written as 4
digit numbers. In the (very unlikely) case that a year before 1000 is used
the number has to start with a 0, e.g. 0950. `<ADDITIONAL_COLUMNS>` can be
anything, there are no further rules at the moment what it can contain.
However, there are strict rules for naming these columns. Allowed are single
names starting with a capital letter without special characters in it except
"_" which is allowed. Examples: "Description" allowed, "More Description" not
allowed, "More_Description" allowed, "123Description" not allowed,
"Description123" allowed. Scripts using this format must be able to ignore
additional columns. For `<YEARS>` there are no specific limitations/requirements
which years should be reported. Scripts dealing with this data must be able
to work with different temporal resolutions. For variables basically
everything can be reported here. Missing values have to be marked with "N/A".
